package com.myinsurance.model.persistant;

import java.util.Date;

/**
 * Database Table Remarks:
 *   客户信息记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_customer_note
 */
public class CustomerNote {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.uid
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.customer_id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.content
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private String content;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.create_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_note.update_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.id
     *
     * @return the value of t_customer_note.id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.id
     *
     * @param id the value for t_customer_note.id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.uid
     *
     * @return the value of t_customer_note.uid
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.uid
     *
     * @param uid the value for t_customer_note.uid
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.customer_id
     *
     * @return the value of t_customer_note.customer_id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.customer_id
     *
     * @param customerId the value for t_customer_note.customer_id
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.content
     *
     * @return the value of t_customer_note.content
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.content
     *
     * @param content the value for t_customer_note.content
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.create_time
     *
     * @return the value of t_customer_note.create_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.create_time
     *
     * @param createTime the value for t_customer_note.create_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_note.update_time
     *
     * @return the value of t_customer_note.update_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_note.update_time
     *
     * @param updateTime the value for t_customer_note.update_time
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}