package com.myinsurance.model.persistant;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_customer
 */
public class Customer {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.uid
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   客户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.age
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   住址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.address
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private String address;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.remark
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.update_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.uid
     *
     * @return the value of t_customer.uid
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.uid
     *
     * @param uid the value for t_customer.uid
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.age
     *
     * @return the value of t_customer.age
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.age
     *
     * @param age the value for t_customer.age
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.address
     *
     * @return the value of t_customer.address
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.address
     *
     * @param address the value for t_customer.address
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.remark
     *
     * @return the value of t_customer.remark
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.remark
     *
     * @param remark the value for t_customer.remark
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_time
     *
     * @param createTime the value for t_customer.create_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.update_time
     *
     * @return the value of t_customer.update_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.update_time
     *
     * @param updateTime the value for t_customer.update_time
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}