package com.myinsurance.model.po;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_customer
 */
public class Customer {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.uid
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   客户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.birthday
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.age
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   基础地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.basic_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String basicAddress;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.detailed_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String detailedAddress;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lng
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Double lng;

    /**
     * Database Column Remarks:
     *   维度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lat
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Double lat;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.remark
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   标注点ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.map_marker_id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Integer mapMarkerId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.update_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    private Date updateTime;

    public Customer() {
    }

    public Customer(Integer id, Integer uid, String name, String sex, Date birthday, Integer age, String phone, String basicAddress, String detailedAddress, Double lng, Double lat, String remark, Integer mapMarkerId, Date createTime, Date updateTime) {
        this.id = id;
        this.uid = uid;
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.age = age;
        this.phone = phone;
        this.basicAddress = basicAddress;
        this.detailedAddress = detailedAddress;
        this.lng = lng;
        this.lat = lat;
        this.remark = remark;
        this.mapMarkerId = mapMarkerId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.uid
     *
     * @return the value of t_customer.uid
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.uid
     *
     * @param uid the value for t_customer.uid
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.birthday
     *
     * @return the value of t_customer.birthday
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.birthday
     *
     * @param birthday the value for t_customer.birthday
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.age
     *
     * @return the value of t_customer.age
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.age
     *
     * @param age the value for t_customer.age
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.basic_address
     *
     * @return the value of t_customer.basic_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getBasicAddress() {
        return basicAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.basic_address
     *
     * @param basicAddress the value for t_customer.basic_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setBasicAddress(String basicAddress) {
        this.basicAddress = basicAddress == null ? null : basicAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.detailed_address
     *
     * @return the value of t_customer.detailed_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getDetailedAddress() {
        return detailedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.detailed_address
     *
     * @param detailedAddress the value for t_customer.detailed_address
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setDetailedAddress(String detailedAddress) {
        this.detailedAddress = detailedAddress == null ? null : detailedAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lng
     *
     * @return the value of t_customer.lng
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lng
     *
     * @param lng the value for t_customer.lng
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lat
     *
     * @return the value of t_customer.lat
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lat
     *
     * @param lat the value for t_customer.lat
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.remark
     *
     * @return the value of t_customer.remark
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.remark
     *
     * @param remark the value for t_customer.remark
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.map_marker_id
     *
     * @return the value of t_customer.map_marker_id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Integer getMapMarkerId() {
        return mapMarkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.map_marker_id
     *
     * @param mapMarkerId the value for t_customer.map_marker_id
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setMapMarkerId(Integer mapMarkerId) {
        this.mapMarkerId = mapMarkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_time
     *
     * @param createTime the value for t_customer.create_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.update_time
     *
     * @return the value of t_customer.update_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.update_time
     *
     * @param updateTime the value for t_customer.update_time
     *
     * @mbg.generated 2018-12-16 19:47:24
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}