package com.myinsurance.model.po;

import java.util.Date;

/**
 * Database Table Remarks:
 *   地图标注
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_map_marker
 */
public class MapMarker {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.id
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.uid
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.lng
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Double lng;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.lat
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Double lat;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.remark
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.create_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map_marker.update_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    private Date updateTime;

    public MapMarker() {
    }

    public MapMarker(Integer id, Integer uid, Double lng, Double lat, String remark, Date createTime, Date updateTime) {
        this.id = id;
        this.uid = uid;
        this.lng = lng;
        this.lat = lat;
        this.remark = remark;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.id
     *
     * @return the value of t_map_marker.id
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.id
     *
     * @param id the value for t_map_marker.id
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.uid
     *
     * @return the value of t_map_marker.uid
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.uid
     *
     * @param uid the value for t_map_marker.uid
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.lng
     *
     * @return the value of t_map_marker.lng
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.lng
     *
     * @param lng the value for t_map_marker.lng
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.lat
     *
     * @return the value of t_map_marker.lat
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.lat
     *
     * @param lat the value for t_map_marker.lat
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.remark
     *
     * @return the value of t_map_marker.remark
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.remark
     *
     * @param remark the value for t_map_marker.remark
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.create_time
     *
     * @return the value of t_map_marker.create_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.create_time
     *
     * @param createTime the value for t_map_marker.create_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map_marker.update_time
     *
     * @return the value of t_map_marker.update_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map_marker.update_time
     *
     * @param updateTime the value for t_map_marker.update_time
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}