package com.myinsurance.dao;

import com.myinsurance.model.po.CustomerHobby;
import com.myinsurance.model.po.CustomerHobbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICustomerHobbyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    long countByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int deleteByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int insert(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int insertSelective(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    List<CustomerHobby> selectByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    CustomerHobby selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByExampleSelective(@Param("record") CustomerHobby record, @Param("example") CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByExample(@Param("record") CustomerHobby record, @Param("example") CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByPrimaryKeySelective(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByPrimaryKey(CustomerHobby record);
}