package com.myinsurance.dao;

import com.myinsurance.model.po.CustomerHobby;
import com.myinsurance.model.po.CustomerHobbyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ICustomerHobbyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    long countByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int deleteByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int insert(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int insertSelective(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    List<CustomerHobby> selectByExample(CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    CustomerHobby selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int updateByExampleSelective(@Param("record") CustomerHobby record, @Param("example") CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int updateByExample(@Param("record") CustomerHobby record, @Param("example") CustomerHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int updateByPrimaryKeySelective(CustomerHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_hobby
     *
     * @mbg.generated 2018-12-09 17:47:02
     */
    int updateByPrimaryKey(CustomerHobby record);

     List<CustomerHobby> selectByUidAndCustomerId(@Param("uid") Integer uid, @Param("customerId") Integer customerId);
}