package com.myinsurance.dao;

import com.myinsurance.model.persistant.CustomerNote;
import com.myinsurance.model.persistant.CustomerNoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ICustomerNoteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    long countByExample(CustomerNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int deleteByExample(CustomerNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int insert(CustomerNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int insertSelective(CustomerNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    List<CustomerNote> selectByExample(CustomerNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    CustomerNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByExampleSelective(@Param("record") CustomerNote record, @Param("example") CustomerNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByExample(@Param("record") CustomerNote record, @Param("example") CustomerNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByPrimaryKeySelective(CustomerNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_note
     *
     * @mbg.generated 2018-11-15 16:09:09
     */
    int updateByPrimaryKey(CustomerNote record);
}