package com.myinsurance.dao;

import com.myinsurance.model.persistant.MapMarker;
import com.myinsurance.model.persistant.MapMarkerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IMapMarkerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    long countByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int deleteByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int insert(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int insertSelective(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    List<MapMarker> selectByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    MapMarker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int updateByExampleSelective(@Param("record") MapMarker record, @Param("example") MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int updateByExample(@Param("record") MapMarker record, @Param("example") MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int updateByPrimaryKeySelective(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-11-08 23:07:39
     */
    int updateByPrimaryKey(MapMarker record);
}