package com.myinsurance.dao;

import com.myinsurance.model.po.MapMarker;
import com.myinsurance.model.po.MapMarkerExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface IMapMarkerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    long countByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int deleteByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int insert(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int insertSelective(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    List<MapMarker> selectByExample(MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    MapMarker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int updateByExampleSelective(@Param("record") MapMarker record, @Param("example") MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int updateByExample(@Param("record") MapMarker record, @Param("example") MapMarkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int updateByPrimaryKeySelective(MapMarker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_map_marker
     *
     * @mbg.generated 2018-12-16 21:21:13
     */
    int updateByPrimaryKey(MapMarker record);

    List<MapMarker> selectByUid(Integer uid);

    MapMarker selectByIdAndUid(@Param("id") Integer id, @Param("uid") Integer uid);
    
}